### ISSUE TITLE
cant see other nodes

### ISSUE THREAD

**Issue by Freaksed** [BrainDoctor/clustercode#2]
i am trying to follow the instructions, but i just cant find a setup where the nodes can see eachother

**Comment by BrainDoctor** [comment]
Hi! It's nice of you to give it a try!

This project is still in development, so not everything is perfect. I need a bit more information on your issue:
1. Which instructions? Have you read the wiki? Specifically https://github.com/BrainDoctor/clustercode/wiki/Cluster-Settings
2. Are you running in Swarm mode? If yes, I fear you need to figure it out by yourselves, as I don't have such a setup and cannot test it.
3. Which image tag are you running? The latest is 1.0.9/stable from Docker Hub as of now.
4. What are your settings/env variables that differ from the defaults?

**Comment by Freaksed** [comment]
hi, thanks for the response. not running swarm, and i set the compose file to latest.
the modified compose file is
version: "2.0"
services:
   clustercode:
     restart: always
     image: braindoctor/clustercode:latest
     container_name: clustercode
     cpu_shares: 512
     ports:
       - "7600:7600/tcp"
     volumes:
       - "~/sorcu/ToConvert:/input"
       - "~/sorcu/Converted:/output"
       - "~/sorcu/clusterconfig:/usr/src/clustercode/config"
     environment:
       - CC_CLUSTER_JGROUPS_TCP_INITAL_HOSTS=192.168.0.13[7600],192.168.0.100[7600],192.168.0.101[7600],192.168.0.102[7600],192.168.0.103[7600]
       - CC_CLUSTER_JGROUPS_EXT_ADDR=192.168.0.104

the first one in the list of hosts there also has the arbiter flag set to true and is being run in docker on my synology nas

i have also tried modifying the properties file directly to set the network settings as follows 

#-------------------------------------------------------------------------------------------------
#  NETWORK and CLUSTER SETTINGS
#-------------------------------------------------------------------------------------------------

# String.
CC_CLUSTER_NAME = clustercode

# Path. Relative | Absolute path. Windows: use "\\" as path separators.
CC_CLUSTER_JGROUPS_CONFIG = config/tcp.xml

# Bool. true | false.
CC_CLUSTER_JGROUPS_PREFER_IPV4 = true

# Integer. 1024 <= x.
CC_CLUSTER_JGROUPS_BIND_PORT = 7600

# String. Format: IPv4 | IPv6 | Jgroups-match | Enum
CC_CLUSTER_JGROUPS_BIND_ADDR = SITE_LOCAL

# String. Format: IPv4 | IPv6. Set to "-" if not used
CC_CLUSTER_JGROUPS_EXT_ADDR = 192.168.0.104

# Array[String]. Format: IPv4[port] | IPv6[port] | DNS hostname[port]
CC_CLUSTER_JGROUPS_TCP_INITIAL_HOSTS = localhost[7600],192.168.0.13[7600],192.168.0.101[7600],192.168.0.102[7600],192.168.0.103[7600],192.168.0.104[7600]

# String. Can be empty.
CC_CLUSTER_JGROUPS_HOSTNAME =

# Integer. 0 <= x. Unit: Hours
CC_CLUSTER_TASK_TIMEOUT = 24

# Bool. true | false.
CC_ARBITER_NODE = false

**Comment by BrainDoctor** [comment]
Try the `stable` image please. Latest is be a bit behind, as I'm doing some internal rework. The stable got a few bugfixes in the meantime.

You don't need to modify the .properties file if you are using environment variables. Env vars always take precedence. Also I noticed a typo in your env var `CC_CLUSTER_JGROUPS_TCP_INITAL_HOSTS`. INITAL should be INITIAL (missing i letter). I don't think that's the issue if you set it again the properties file though.

I assume that every other node has similar initial hosts?

**Comment by Freaksed** [comment]
aha, fixing the typo and switching to stable seems to have helped, thanks :)

**Comment by BrainDoctor** [comment]
good to know.  If you have further problems or suggestions please report them :)
